# Generated by Django 4.0 on 2022-03-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_subject_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_1',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_3',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_4',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
