# Generated by Django 4.0 on 2022-03-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_question_choices_question_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
