# Generated by Django 4.0 on 2022-03-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_tests_score_user_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
