# Generated by Django 4.0 on 2022-03-15 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_score_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='tests',
        ),
        migrations.AddField(
            model_name='test',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subject'),
        ),
    ]
