# Generated by Django 4.0 on 2022-04-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='number_of_questions',
            field=models.IntegerField(null=True),
        ),
    ]
